-- AlterTable
ALTER TABLE "NOTIFICATION" ADD COLUMN     "id_Realisation" INTEGER;

-- CreateTable
CREATE TABLE "REALISATION" (
    "ID_Realisation" SERIAL NOT NULL,
    "Date_Realise" TIMESTAMP(3) NOT NULL,
    "Note" DOUBLE PRECISION,
    "Statut_Valide" BOOLEAN NOT NULL DEFAULT false,
    "id_SActes" INTEGER NOT NULL,
    "id_Etudiant" INTEGER NOT NULL,
    "id_Prof" INTEGER,
    "id_Paie" INTEGER,

    CONSTRAINT "REALISATION_pkey" PRIMARY KEY ("ID_Realisation")
);

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_id_Realisation_fkey" FOREIGN KEY ("id_Realisation") REFERENCES "REALISATION"("ID_Realisation") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REALISATION" ADD CONSTRAINT "REALISATION_id_SActes_fkey" FOREIGN KEY ("id_SActes") REFERENCES "SOUS_ACTES"("ID_SActes") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REALISATION" ADD CONSTRAINT "REALISATION_id_Etudiant_fkey" FOREIGN KEY ("id_Etudiant") REFERENCES "ETUDIANT"("ID_Etudiant") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REALISATION" ADD CONSTRAINT "REALISATION_id_Prof_fkey" FOREIGN KEY ("id_Prof") REFERENCES "PROFESSEURS"("ID_Prof") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REALISATION" ADD CONSTRAINT "REALISATION_id_Paie_fkey" FOREIGN KEY ("id_Paie") REFERENCES "PAIEMENT"("ID_Paie") ON DELETE SET NULL ON UPDATE CASCADE;
