-- CreateEnum
CREATE TYPE "TypeNotification" AS ENUM ('REALISATION', 'EVALUATION', 'PAIEMENT', 'VALIDATION');

-- CreateTable
CREATE TABLE "NOTIFICATION" (
    "ID_Notification" SERIAL NOT NULL,
    "Message" TEXT NOT NULL,
    "Type" "TypeNotification" NOT NULL,
    "Date_Envoi" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Lu" BOOLEAN NOT NULL DEFAULT false,
    "id_SActes" INTEGER,
    "id_Paie" INTEGER,
    "id_Etudiant" INTEGER,
    "id_Prof" INTEGER,
    "id_Admin" INTEGER,

    CONSTRAINT "NOTIFICATION_pkey" PRIMARY KEY ("ID_Notification")
);

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_id_SActes_fkey" FOREIGN KEY ("id_SActes") REFERENCES "SOUS_ACTES"("ID_SActes") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_id_Paie_fkey" FOREIGN KEY ("id_Paie") REFERENCES "PAIEMENT"("ID_Paie") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_id_Etudiant_fkey" FOREIGN KEY ("id_Etudiant") REFERENCES "ETUDIANT"("ID_Etudiant") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_id_Prof_fkey" FOREIGN KEY ("id_Prof") REFERENCES "PROFESSEURS"("ID_Prof") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_id_Admin_fkey" FOREIGN KEY ("id_Admin") REFERENCES "ADMINISTRATEUR"("ID_Admin") ON DELETE SET NULL ON UPDATE CASCADE;
