-- DropForeignKey
ALTER TABLE "public"."SOUS_ACTES" DROP CONSTRAINT "SOUS_ACTES_id_Etudiant_fkey";

-- AlterTable
ALTER TABLE "SOUS_ACTES" ALTER COLUMN "id_Etudiant" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "SOUS_ACTES" ADD CONSTRAINT "SOUS_ACTES_id_Etudiant_fkey" FOREIGN KEY ("id_Etudiant") REFERENCES "ETUDIANT"("ID_Etudiant") ON DELETE SET NULL ON UPDATE CASCADE;
