-- CreateTable
CREATE TABLE "ADMINISTRATEUR" (
    "ID_Admin" SERIAL NOT NULL,
    "Nom_Admin" TEXT NOT NULL,
    "Email_Admin" TEXT NOT NULL,
    "MotPass_Admin" TEXT NOT NULL,
    "id_Quotas" INTEGER,
    "id_Paie" INTEGER,

    CONSTRAINT "ADMINISTRATEUR_pkey" PRIMARY KEY ("ID_Admin")
);

-- CreateTable
CREATE TABLE "ETUDIANT" (
    "ID_Etudiant" SERIAL NOT NULL,
    "FullName_Et" TEXT NOT NULL,
    "Email_Et" TEXT NOT NULL,
    "Annee_Et" TEXT NOT NULL,
    "Dette" DOUBLE PRECISION,
    "MotPass_Et" TEXT NOT NULL,
    "id_Paie" INTEGER,
    "id_Actes" INTEGER,

    CONSTRAINT "ETUDIANT_pkey" PRIMARY KEY ("ID_Etudiant")
);

-- CreateTable
CREATE TABLE "PROFESSEURS" (
    "ID_Prof" SERIAL NOT NULL,
    "Nom_Prof" TEXT NOT NULL,
    "Email_Prof" TEXT NOT NULL,
    "MotPass_Prof" TEXT NOT NULL,
    "id_SActes" INTEGER,

    CONSTRAINT "PROFESSEURS_pkey" PRIMARY KEY ("ID_Prof")
);

-- CreateTable
CREATE TABLE "DEPARTEMENT" (
    "ID_Dep" SERIAL NOT NULL,
    "Nom_Dep" TEXT NOT NULL,
    "id_Et" INTEGER,
    "id_Actes" INTEGER,

    CONSTRAINT "DEPARTEMENT_pkey" PRIMARY KEY ("ID_Dep")
);

-- CreateTable
CREATE TABLE "ACTES" (
    "ID_Actes" SERIAL NOT NULL,
    "Desc_Actes" TEXT NOT NULL,
    "id_SActes" INTEGER,

    CONSTRAINT "ACTES_pkey" PRIMARY KEY ("ID_Actes")
);

-- CreateTable
CREATE TABLE "SOUS_ACTES" (
    "ID_SActes" SERIAL NOT NULL,
    "Desc_SActes" TEXT NOT NULL,
    "Prix" DOUBLE PRECISION NOT NULL,
    "Note" DOUBLE PRECISION,
    "Date_Realise" TIMESTAMP(3),
    "Statut_Valide" BOOLEAN NOT NULL,

    CONSTRAINT "SOUS_ACTES_pkey" PRIMARY KEY ("ID_SActes")
);

-- CreateTable
CREATE TABLE "QUOTAS" (
    "ID_Quotas" SERIAL NOT NULL,
    "Annee" TEXT NOT NULL,
    "Nombre" INTEGER NOT NULL,
    "Date_Debut" TIMESTAMP(3) NOT NULL,
    "Date_Fin" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "QUOTAS_pkey" PRIMARY KEY ("ID_Quotas")
);

-- CreateTable
CREATE TABLE "PAIEMENT" (
    "ID_Paie" SERIAL NOT NULL,
    "Montant" DOUBLE PRECISION NOT NULL,
    "Type_Paie" TEXT NOT NULL,
    "Date_Paie" TIMESTAMP(3) NOT NULL,
    "Statut_Paie" TEXT NOT NULL,

    CONSTRAINT "PAIEMENT_pkey" PRIMARY KEY ("ID_Paie")
);

-- CreateIndex
CREATE UNIQUE INDEX "ADMINISTRATEUR_Email_Admin_key" ON "ADMINISTRATEUR"("Email_Admin");

-- CreateIndex
CREATE UNIQUE INDEX "ETUDIANT_Email_Et_key" ON "ETUDIANT"("Email_Et");

-- CreateIndex
CREATE UNIQUE INDEX "PROFESSEURS_Email_Prof_key" ON "PROFESSEURS"("Email_Prof");

-- AddForeignKey
ALTER TABLE "ADMINISTRATEUR" ADD CONSTRAINT "ADMINISTRATEUR_id_Quotas_fkey" FOREIGN KEY ("id_Quotas") REFERENCES "QUOTAS"("ID_Quotas") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ADMINISTRATEUR" ADD CONSTRAINT "ADMINISTRATEUR_id_Paie_fkey" FOREIGN KEY ("id_Paie") REFERENCES "PAIEMENT"("ID_Paie") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ETUDIANT" ADD CONSTRAINT "ETUDIANT_id_Paie_fkey" FOREIGN KEY ("id_Paie") REFERENCES "PAIEMENT"("ID_Paie") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ETUDIANT" ADD CONSTRAINT "ETUDIANT_id_Actes_fkey" FOREIGN KEY ("id_Actes") REFERENCES "ACTES"("ID_Actes") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROFESSEURS" ADD CONSTRAINT "PROFESSEURS_id_SActes_fkey" FOREIGN KEY ("id_SActes") REFERENCES "SOUS_ACTES"("ID_SActes") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DEPARTEMENT" ADD CONSTRAINT "DEPARTEMENT_id_Et_fkey" FOREIGN KEY ("id_Et") REFERENCES "ETUDIANT"("ID_Etudiant") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DEPARTEMENT" ADD CONSTRAINT "DEPARTEMENT_id_Actes_fkey" FOREIGN KEY ("id_Actes") REFERENCES "ACTES"("ID_Actes") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTES" ADD CONSTRAINT "ACTES_id_SActes_fkey" FOREIGN KEY ("id_SActes") REFERENCES "SOUS_ACTES"("ID_SActes") ON DELETE SET NULL ON UPDATE CASCADE;
