-- DropForeignKey
ALTER TABLE "public"."PAIEMENT" DROP CONSTRAINT "PAIEMENT_id_Admin_fkey";

-- AlterTable
ALTER TABLE "PAIEMENT" ALTER COLUMN "id_Admin" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "PAIEMENT" ADD CONSTRAINT "PAIEMENT_id_Admin_fkey" FOREIGN KEY ("id_Admin") REFERENCES "ADMINISTRATEUR"("ID_Admin") ON DELETE SET NULL ON UPDATE CASCADE;
