-- CreateTable
CREATE TABLE "HISTORIQUE_PAIEMENT" (
    "ID_Hist" SERIAL NOT NULL,
    "Action" TEXT NOT NULL,
    "AncienStatut" "StatutPaiement" NOT NULL,
    "NouveauStatut" "StatutPaiement" NOT NULL,
    "Montant" DOUBLE PRECISION,
    "Montant_Restant" DOUBLE PRECISION,
    "Date_Action" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id_Paie" INTEGER NOT NULL,
    "id_Admin" INTEGER,

    CONSTRAINT "HISTORIQUE_PAIEMENT_pkey" PRIMARY KEY ("ID_Hist")
);

-- AddForeignKey
ALTER TABLE "HISTORIQUE_PAIEMENT" ADD CONSTRAINT "HISTORIQUE_PAIEMENT_id_Paie_fkey" FOREIGN KEY ("id_Paie") REFERENCES "PAIEMENT"("ID_Paie") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HISTORIQUE_PAIEMENT" ADD CONSTRAINT "HISTORIQUE_PAIEMENT_id_Admin_fkey" FOREIGN KEY ("id_Admin") REFERENCES "ADMINISTRATEUR"("ID_Admin") ON DELETE SET NULL ON UPDATE CASCADE;
